### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alexandretessarollo** [own-pt/own-en#7]
Which should be/is our license? [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)?

We already have several tools available here, and recently we've been adding to the actual WN resource. So far the work put in here has not infringed copyrights, but we might consider adding some guidelines on this aspect for contributions as well. To do so we must first set our license.

**Comment by arademaker** [comment]
You are right. I added d42e258cdfbaae459e3f91c9179b20c583d3eaa4.

**Comment by arademaker** [comment]
For the guidelines, I welcome any initial idea that we can add in the README file as a section. Please PR is welcome.
